spring:
  config:
    import: classpath:oss.properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/avatar/
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  application:
    name: lf-admin
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lfadmin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    timeout: 10000
    expire: 180000
    database: 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.lf.entity
  configuration:
    map-underscore-to-camel-case: true
    #  开启详细的sql日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: isDelete




#自定义配置

logging:
  level:
    com:
      lf:
        dao: debug
server:
  port: 8080

jwt:
  secret: com.lf
  expiration: 180000

request:
  captcha:
    url: /captcha
  login:
    url: /api/user/login
